### PR TITLE
Add STARmap to library preparation protocol menu in expression matrix upload (SCP-3261)

### PR DESCRIPTION
**Pull request by eweitz**
This adds [STARmap](https://science.sciencemag.org/content/361/6400/eaat5691) to the "Library Preparation Protocol" dropdown menu in the upload wizard's "Expression Matrix" tab.

STARmap has no EFO entry -- getting one is upstream work-in-progress.  So users can't specify STARmap in metadata files yet.  This is OK, as these expression file menu selections aren't yet coordinated with metadata validation and faceted search.  Such coordination is a future goal of [file-level metadata handling](https://docs.google.com/document/d/1xeTo-8bfyzDgoBKIycA0zIz3LB9XmFmRG0QJEpsyXV4/edit).

To test:
1. Go to upload wizard of an existing study
2. Change "Library preparation protocol" to "STARmap"
3. Save, refresh, and verify "STARmap" selection persists
4. Restore menu value from before step 2.

STARmap_in_library_preparation_protocol_menu_SCP_2021-04-13

This satisfies SCP-3261.

### CODE REVIEW

**Review by devonbush — APPROVED** [review]
Looks good.  Your screenshot suggests that after another couple of these, we'll probably want to use a different select widget for picking library prep. protocol

**Review by jlchang — APPROVED** [review]
Other than the build failure, everything looks fine.

If the errors (partial list below) are spurrious, please tag the PR with the `build-failure: false-positive` label. Thanks!

At least one module failed to build and saw these:
FAIL test/js/search/gene-search-view.test.js
  ● Test suite failed to run
FAIL test/js/resultsPanel.test.js
  ● Test suite failed to run
FAIL test/js/studyResults.test.js
  ● Test suite failed to run
and these:
1) Error:
CacheManagementTest#test_manage_cache_entries:
NoMethodError: undefined method `expression_query_path' for #<CacheManagementTest:0x0000555fb1e065f8>

2) Error:
GenericProfilerTest#test_should_profile_method:
Errno::ENOENT: No such file or directory - getcwd
 
  3) Error:
GenericProfilerTest#test_should_profile_clustering_methods:
Errno::ENOENT: No such file or directory - getcwd

  4) Error:
GenericProfilerTest#test_should_profile_gene_expression_methods:
Errno::ENOENT: No such file or directory - getcwd

**Comment by eweitz** [comment]
> the `build-failure: false-positive` label

Great reminder.  The first of those errors is a true positive, caused by PR #978.  I'll fix that and open a separate PR as it'll warrant separate review from this trivial UI change.

I'll be sure to use `build-failure: false-positive` for future cases where all tests are failures that aren't bugs.

**Review by bistline — APPROVED** [review]
